const refs = {
    linkAboutProject: document.querySelector('.link-about-project'),
    linkReviews: document.querySelector('.link-reviews'),
    linkFaq: document.querySelector('.link-faq'),
    aboutboutProjectSection: document.querySelector('.about-project'),
    reviewsSection: document.querySelector('.reviews'),
    faqSection: document.querySelector('.faq'),
    faqArrows: document.querySelectorAll(".faq__item-arrow"),
    countdownEl: document.querySelector('.hero__timer'),
    openMenuBtn: document.querySelector(".nav__btn-mob-menu-open"),
    closeMenuBtn: document.querySelector(".nav__btn-mob-menu-close"),
    mobMenuBackdrop: document.querySelector(".mob-menu__backdrop"),
    mobMenu: document.querySelector(".mob-menu"),
    linkAboutProjectMob: document.querySelector('.link-about-project-mob'),
    linkReviewsMob: document.querySelector('.link-reviews-mob'),
    linkFaqMob: document.querySelector('.link-faq-mob'),
};

export const {
    linkAboutProject,
    linkReviews,
    linkFaq,
    aboutboutProjectSection,
    reviewsSection,
    faqSection,
    faqArrows,
    countdownEl,
    openMenuBtn,
    closeMenuBtn,
    mobMenuBackdrop,
    mobMenu,
    linkAboutProjectMob,
    linkReviewsMob,
    linkFaqMob,
} = refs;